# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-22 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0003_auto_20181127_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thought',
            options={'ordering': ['-recorder_at']},
        ),
    ]
