# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-22 09:51
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=' ', editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
